if(typeof postscribe=="undefined"){(function(){var b=(function(){var k={};var l;var j=this.document.createElement("div");l="<P><I></P></I>";j.innerHTML=l;k.tagSoup=j.innerHTML!==l;j.innerHTML="<P><i><P></P></i></P>";k.selfClose=j.childNodes.length===2;return k
})();var g=/^<([\-A-Za-z0-9_]+)((?:\s+[\w\-]+(?:\s*=?\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/;var f=/^<\/([\-A-Za-z0-9_]+)[^>]*>/;var a=/(?:([\-A-Za-z0-9_]+)\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))|(?:([\-A-Za-z0-9_]+)(\s|$)+)/g;
var h=/^(checked|compact|declare|defer|disabled|ismap|multiple|nohref|noresize|noshade|nowrap|readonly|selected)$/i;var c=false;function e(w,x){w=w||"";x=x||{};for(var u in b){if(b.hasOwnProperty(u)){if(x.autoFix){x["fix_"+u]=true}x.fix=x.fix||x["fix_"+u]}}var s=[];
var m=document.createElement("div");var t=function(z){if((typeof z==="string")&&(z.indexOf("&")!==-1)){m.innerHTML=z;return m.textContent||m.innerText||z}else{return z}};var n=function(z){w+=z};var y=function(z){w=z+w};var j={comment:/^<!--/,endTag:/^<\//,atomicTag:/^<\s*(script|style|noscript|iframe|textarea)[\s\/>]/i,startTag:/^</,chars:/^[^<]/};
var q={comment:function(){var z=w.indexOf("-->");if(z>=0){return{content:w.substr(4,z-1),length:z+3}}},endTag:function(){var z=w.match(f);if(z){return{tagName:z[1],length:z[0].length}}},atomicTag:function(){var B=q.startTag();if(B){var A=w.slice(B.length);if(A.match(new RegExp("</\\s*"+B.tagName+"\\s*>","i"))){var z=A.match(new RegExp("([\\s\\S]*?)</\\s*"+B.tagName+"\\s*>","i"));
if(z){return{tagName:B.tagName,attrs:B.attrs,content:z[1],length:z[0].length+B.length}}}}},startTag:function(){var z=w.indexOf(">");if(z===-1){return null}var C=w.match(g);if(C){var B={};var A={};var D=C[2];C[2].replace(a,function(F,E){if(!(arguments[2]||arguments[3]||arguments[4]||arguments[5])){B[E]=null
}else{if(arguments[5]){B[arguments[5]]="";A[E]=true}else{var G=arguments[2]||arguments[3]||arguments[4]||h.test(E)&&E||"";B[E]=t(G)}}D=D.replace(F,"")});return{tagName:C[1],attrs:B,booleanAttrs:A,rest:D,unary:!!C[3],length:C[0].length}}},chars:function(){var z=w.indexOf("<");
return{length:z>=0?z:w.length}}};var r=function(){for(var A in j){if(j[A].test(w)){var z=q[A]();if(z){z.type=z.type||A;z.text=w.substr(0,z.length);w=w.slice(z.length);return z}return null}}};var l=function(A){var z;while((z=r())){if(A[z.type]&&A[z.type](z)===false){return
}}};var o=function(){var z=w;w="";return z};var k=function(){return w};if(x.fix){(function(){var z=/^(AREA|BASE|BASEFONT|BR|COL|FRAME|HR|IMG|INPUT|ISINDEX|LINK|META|PARAM|EMBED)$/i;var D=/^(COLGROUP|DD|DT|LI|OPTIONS|P|TD|TFOOT|TH|THEAD|TR)$/i;var F=[];F.last=function(){return this[this.length-1]
};F.lastTagNameEq=function(J){var K=this.last();return K&&K.tagName&&K.tagName.toUpperCase()===J.toUpperCase()};F.containsTagName=function(L){for(var K=0,J;(J=this[K]);K++){if(J.tagName===L){return true}}return false};var E=function(J){if(J&&J.type==="startTag"){J.unary=z.test(J.tagName)||J.unary;
J.html5Unary=!/\/>$/.test(J.text)}return J};var C=r;var I=function(){var K=w;var J=E(C());w=K;return J};var B=function(){var J=F.pop();y("</"+J.tagName+">")};var A={startTag:function(J){var K=J.tagName;if(K.toUpperCase()==="TR"&&F.lastTagNameEq("TABLE")){y("<TBODY>");
G()}else{if(x.fix_selfClose&&D.test(K)&&F.containsTagName(K)){if(F.lastTagNameEq(K)){B()}else{y("</"+J.tagName+">");G()}}else{if(!J.unary){F.push(J)}}}},endTag:function(J){var K=F.last();if(K){if(x.fix_tagSoup&&!F.lastTagNameEq(J.tagName)){B()}else{F.pop()}}else{if(x.fix_tagSoup){H()
}}}};var H=function(){C();G()};var G=function(){var J=I();if(J&&A[J.type]){A[J.type](J)}};r=function(){G();return E(C())}})()}return{append:n,readToken:r,readTokens:l,clear:o,rest:k,stack:s}}e.supports=b;e.tokenToString=function(j){var k={comment:function(l){return"<!--"+l.content
},endTag:function(l){return"</"+l.tagName+">"},atomicTag:function(l){return k.startTag(l)+l.content+k.endTag(l)},startTag:function(l){var o="<"+l.tagName;for(var m in l.attrs){o+=" "+m;var n=l.attrs[m];if(typeof l.booleanAttrs=="undefined"||typeof l.booleanAttrs[m]=="undefined"){o+='="'+(n?n.replace(/(^|[^\\])"/g,'$1\\"'):"")+'"'
}}if(l.rest){o+=l.rest}return o+(l.unary&&!l.html5Unary?"/>":">")},chars:function(l){return l.text}};return k[j.type](j)};e.escapeAttributes=function(l){var j={};for(var k in l){var m=l[k];j[k]=m&&m.replace(/(^|[^\\])"/g,'$1\\"')}return j};for(var d in b){e.browserHasFlaw=e.browserHasFlaw||(!b[d])&&d
}this.htmlParser=e})();(function(){function g(){}var f={afterAsync:g,afterDequeue:g,afterStreamStart:g,afterWrite:g,autoFix:true,beforeEnqueue:g,beforeWriteToken:function(t){return t},beforeWrite:function(t){return t},done:g,error:function(t){throw t},releaseAsync:false};
var a=this;var j=void 0;function k(t){return t!==j&&t!==null}if(a.postscribe){return}var r=false;var o=Array.prototype.slice;function b(t){return"function"===typeof t}function l(u,x,y){var w,t=(u&&u.length)||0;for(w=0;w<t;w++){x.call(y,u[w],w)}}function n(w,u,x){var t;
for(t in w){if(w.hasOwnProperty(t)){u.call(x,t,w[t])}}}function m(u,t){n(t,function(w,x){u[w]=x});return u}function d(t,u){t=t||{};n(u,function(w,x){if(!k(t[w])){t[w]=x}});return t}function e(w){try{return o.call(w)}catch(u){var t=[];l(w,function(x){t.push(x)
});return t}}var q=function(t){return t[t.length-1]};function c(t){return !t||!("tagName" in t)?!1:!!~t.tagName.toLowerCase().indexOf("script")}function s(t){return !t||!("tagName" in t)?!1:!!~t.tagName.toLowerCase().indexOf("style")}var h=(function(){var t="data-ps-";
function u(z,y,A){var x=t+y;if(arguments.length===2){var B=z.getAttribute(x);return !k(B)?B:String(B)}else{if(k(A)&&A!==""){z.setAttribute(x,A)}else{z.removeAttribute(x)}}}function w(x,y){var z=x.ownerDocument;m(this,{root:x,options:y,win:z.defaultView||z.parentWindow,doc:z,parser:htmlParser("",{autoFix:y.autoFix}),actuals:[x],proxyHistory:"",proxyRoot:z.createElement(x.nodeName),scriptStack:[],writeQueue:[]});
u(this.proxyRoot,"proxyof",0)}w.prototype.write=function(){[].push.apply(this.writeQueue,arguments);var x;while(!this.deferredRemote&&this.writeQueue.length){x=this.writeQueue.shift();if(b(x)){this.callFunction(x)}else{this.writeImpl(x)}}};w.prototype.callFunction=function(y){var x={type:"function",value:y.name||y.toString()};
this.onScriptStart(x);y.call(this.win,this.doc);this.onScriptDone(x)};w.prototype.writeImpl=function(z){this.parser.append(z);var y,B=[],x,A;while((y=this.parser.readToken())&&!(x=c(y))&&!(A=s(y))){y=this.options.beforeWriteToken(y);if(y){B.push(y)}}this.writeStaticTokens(B);
if(x){this.handleScriptToken(y)}if(A){this.handleStyleToken(y)}};w.prototype.writeStaticTokens=function(y){var x=this.buildChunk(y);if(!x.actual){return}x.html=this.proxyHistory+x.actual;this.proxyHistory+=x.proxy;this.proxyRoot.innerHTML=x.html;if(r){x.proxyInnerHTML=this.proxyRoot.innerHTML
}this.walkChunk();if(r){x.actualInnerHTML=this.root.innerHTML}return x};w.prototype.buildChunk=function(A){var z=this.actuals.length,x=[],B=[],y=[];l(A,function(D){var C=htmlParser.tokenToString(D);x.push(C);if(D.attrs){if(!(/^noscript$/i).test(D.tagName)){var E=z++;
B.push(C.replace(/(\/?>)/," "+t+"id="+E+" $1"));if(D.attrs.id!=="ps-script"&&D.attrs.id!=="ps-style"){y.push(D.type==="atomicTag"?"":"<"+D.tagName+" "+t+"proxyof="+E+(D.unary?" />":">"))}}}else{B.push(C);y.push(D.type==="endTag"?C:"")}});return{tokens:A,raw:x.join(""),actual:B.join(""),proxy:y.join("")}
};w.prototype.walkChunk=function(){var B,x=[this.proxyRoot];while(k(B=x.shift())){var A=B.nodeType===1;var z=A&&u(B,"proxyof");if(!z){if(A){this.actuals[u(B,"id")]=B;u(B,"id",null)}var y=B.parentNode&&u(B.parentNode,"proxyof");if(y){this.actuals[y].appendChild(B)
}}x.unshift.apply(x,e(B.childNodes))}};w.prototype.handleScriptToken=function(x){var y=this.parser.clear();if(y){this.writeQueue.unshift(y)}x.src=x.attrs.src||x.attrs.SRC;x=this.options.beforeWriteToken(x);if(!x){return}if(x.src&&this.scriptStack.length){this.deferredRemote=x
}else{this.onScriptStart(x)}var z=this;this.writeScriptToken(x,function(){z.onScriptDone(x)})};w.prototype.handleStyleToken=function(x){var y=this.parser.clear();if(y){this.writeQueue.unshift(y)}x.type=x.attrs.type||x.attrs.TYPE||"text/css";x=this.options.beforeWriteToken(x);
if(x){this.writeStyleToken(x)}if(y){this.write()}};w.prototype.writeStyleToken=function(x){var y=this.buildStyle(x);this.insertStyle(y);if(x.content){if(y.styleSheet&&!y.sheet){y.styleSheet.cssText=x.content}else{y.appendChild(this.doc.createTextNode(x.content))
}}};w.prototype.buildStyle=function(x){var y=this.doc.createElement(x.tagName);y.setAttribute("type",x.type);n(x.attrs,function(z,A){y.setAttribute(z,A)});return y};w.prototype.insertStyle=function(x){this.writeImpl('<span id="ps-style"/>');var y=this.doc.getElementById("ps-style");
y.parentNode.replaceChild(x,y)};w.prototype.onScriptStart=function(x){x.outerWrites=this.writeQueue;this.writeQueue=[];this.scriptStack.unshift(x)};w.prototype.onScriptDone=function(x){if(x!==this.scriptStack[0]){this.options.error({message:"Bad script nesting or script finished twice"});
return}this.scriptStack.shift();this.write.apply(this,x.outerWrites);if(!this.scriptStack.length&&this.deferredRemote){this.onScriptStart(this.deferredRemote);this.deferredRemote=null}};w.prototype.writeScriptToken=function(y,x){var z=this.buildScript(y);var B=this.shouldRelease(z);
var A=this.options.afterAsync;if(y.src){z.src=y.src;this.scriptLoadHandler(z,!B?function(){x();A()}:A)}try{this.insertScript(z);if(!y.src||B){x()}}catch(C){this.options.error(C);x()}};w.prototype.buildScript=function(x){var y=this.doc.createElement(x.tagName);
n(x.attrs,function(z,A){y.setAttribute(z,A)});if(x.content){y.text=x.content}return y};w.prototype.insertScript=function(x){this.writeImpl('<span id="ps-script"/>');var y=this.doc.getElementById("ps-script");y.parentNode.replaceChild(x,y)};w.prototype.scriptLoadHandler=function(B,x){function A(){B=B.onload=B.onreadystatechange=B.onerror=null
}var z=this.options.error;function C(){A();x()}function y(D){A();z(D);x()}m(B,{onload:function(){C()},onreadystatechange:function(){if(/^(loaded|complete)$/.test(B.readyState)){C()}},onerror:function(){y({message:"remote script failed "+B.src})}})};w.prototype.shouldRelease=function(x){var y=/^script$/i.test(x.nodeName);
return !y||!!(this.options.releaseAsync&&x.src&&x.hasAttribute("async"))};return w}());a.postscribe=(function(){var x=0;var t=[];var y=null;function u(){var B=t.shift();var A;if(B){A=q(B);A.afterDequeue();B.stream=z.apply(null,B);A.afterStreamStart()}}function z(G,D,C){y=new h(G,C);
y.id=x++;y.name=C.name||y.id;w.streams[y.name]=y;var H=G.ownerDocument;var B={close:H.close,open:H.open,write:H.write,writeln:H.writeln};function F(I){I=C.beforeWrite(I);y.write(I);C.afterWrite(I)}m(H,{close:g,open:g,write:function(){return F(e(arguments).join(""))
},writeln:function(){return F(e(arguments).join("")+"\n")}});var E=y.win.onerror||g;y.win.onerror=function(K,J,I){C.error({msg:K+" - "+J+":"+I});E.apply(y.win,arguments)};y.write(D,function A(){m(H,B);y.win.onerror=E;C.done();y=null;u()});return y}function w(D,C,B){if(b(B)){B={done:B}
}B=d(B,f);D=(/^#/).test(D)?a.document.getElementById(D.substr(1)):D.jquery?D[0]:D;var A=[D,C,B];D.postscribe={cancel:function(){if(A.stream){A.stream.abort()}else{A[1]=g}}};B.beforeEnqueue(A);t.push(A);if(!y){u()}return D.postscribe}return m(w,{streams:{},queue:t,WriteStream:h})
}())}())}if(typeof LWtpo==="undefined"){var LWtpo={url:(("https:"==document.location.protocol?"https://":"http://")+"go.linkwi.se/"),tm:[],lwde_vars:{},pc:[],p:0,dc:1,cr:978,sr:0,cv:0,rtg:1,max_prod_url_part_length:1800,dg:function(a){if(typeof console==="object"){console.log(a)
}},loadScript:function(a,e){function d(){this.onreadystatechange=null;this.onload=null;window.setTimeout(e,20)}var b=function(){var f=this.readyState;if(f=="loaded"||f=="complete"){d()}};var c=document.createElement("script");c.type="text/javascript";if(e){c.onreadystatechange=b;
c.onload=d}c.src=a;document.getElementsByTagName("head")[0].appendChild(c)},track:function(k){var q="undefined";var o="string";var e="object";var b=!1,d=!1;if(typeof k.lw!==q&&typeof k.lw.q===e){for(var l in k.lw.q){var a=k.lw.q[l];if(typeof a[0]===o){a[0]=a[0].toLowerCase();
if(a[0]==="clickid"&&typeof a[1]!==q){d=a[1]}else{if(a[0]==="setprogram"&&typeof a[1]!==q){b=parseInt(a[1])}}}}}if(d&&b){this.loadScript(this.url+"delivery/lwc/lwc.js",function(){Linkwise.tracker(b,d)})}else{var g,h;var n=k.location.href.slice(window.location.href.indexOf("?")+1).split("&");
var m="lkws_";var c=m.length;for(var f=0;f<n.length;f++){g=n[f].split("=");if(g[0].substring(0,c)==m){h=g;this.loadScript(this.url+"delivery/lwc/lwc.js",function(){Linkwise.tracker(h[0].substring(c))})}}}},dw:function(a){postscribe(document.getElementsByTagName("BODY")[0],a)
},pida:function(g){var k=[];var d;var m="undefined";var b;var j=0;var h;var f;var c;for(i=0,tl=this.tm.length;i<tl;i++){b=this.tm[i];d="["+i+"]=";h=0;c=[];f="pid"+d+g(b.id);h+=f.length;c.push(f);if(typeof b.price!=m){f="price"+d+g(b.price);h+=f.length;c.push(f)
}if(typeof b.quantity!=m){f="qty"+d+g(b.quantity);h+=f.length;c.push(f)}if(j+h<=this.max_prod_url_part_length){j+=h;k=k.concat(c)}else{break}}return"&"+k.join("&")},fi:function(b,a){return a?String(b).replace(".","").replace(",","."):b},dk:function(a){return a?",":"."
},zk:function(f,c,e,d,b,a){if((typeof c==a)||(typeof e==a)){this.dg("missing item payout category")}else{v=parseInt(c);if(isNaN(v)){this.dg("invalid item payout category id: "+c)}else{c=v;v=parseFloat(this.fi(e,b));if(isNaN(v)){this.dg("invalid payout category price: "+e)
}else{if(typeof d==a){d=1}e=Math.round(v*100)*d;if(typeof f[c]==a){f[c]=e}else{f[c]+=e}}}}},ic:function(a){if(typeof a!="undefined"){if(a=="."){return 0}}return 1},cs:function(b){var a=document.createElement("script");a.type="text/javascript";a.async="on";a.src=this.url+b;
document.body.appendChild(a)},is:function(b,a){this.cs("rtg/"+b+".php?format=jsonp&cam_id="+this.p+a)},lwde:(function(){var a="";var b=!1;return function(g,d){if(!b){var c=typeof d!=="undefined"&&d.indexOf("pid")!==-1;for(var f in this.lwde_vars){if(this.lwde_vars.hasOwnProperty(f)){if(!c&&f!=="page"){c=1
}a+="&"+g(f)+"="+g(this.lwde_vars[f])}}if(c){this.cs("delivery/lwde.php?format=jsonp&cam_id="+this.p+a+d);this.lwde_vars={}}b=1}}})(),lwde_add:function(b,c){var a="undefined";if(typeof b!==a&&typeof c!==a){this.lwde_vars[b]=c}},rc:function(a,h){if(typeof a==="object"&&typeof h==="number"){var n,j;
n=0;for(j in a){n++}if(h>0&&n>0){var l,e=0,q=[],f=0,d=0,c=0;for(l in a){e+=a[l]}if(e<=h){for(l in a){a[l]=0}}else{for(l in a){q[l]=a[l]/e;a[l]=a[l]-(q[l]*h);if(a[l]<=0){a[l]=0}else{a[l]=Math.round(a[l])}if(a[l]>c){c=a[l];d=l}f+=a[l]}var m=e-h>0?e-h:0;if(m!==f){var o=m-f;
if(o>0){a[d]+=o}else{if(a[d]-Math.abs(o)>=0){a[d]+=o}else{var b,g;while(o!==0&&c!==0){b=a[d];a[d]+=o;if(a[d]<0){a[d]=0}g=Math.abs(o);o+=(b>=g?g:b);d=0;c=0;for(l in a){if(a[l]>c){c=a[l];d=l}}}}}}}}}return a},main:function(o,g){var D="object";var B="undefined";
if(typeof g===B){g=0}if((typeof o.lw!=B)&&(typeof o.lw.q==D)){var y="string";var J,q,G,h,r;var F=p="";while(G=o.lw.q.shift()){q=G[1];if(typeof G[0]==y){switch(G[0].toLowerCase()){case"setprogram":if(typeof q!=B){this.p=parseInt(q);if(isNaN(this.p)){this.p=null
}else{this.sr=1}}else{this.dg("invalid setPprogram")}break;case"setemail":break;case"viewhome":J=1;break;case"additem":r=typeof q;if(r==y){var x={};x.id=q;q=x}if(r!=B){this.tm.push(q)}else{this.dg("addItem without id")}break;case"listitems":J=2;break;case"viewitem":J=3;
break;case"viewcart":J=4;break;case"checkout":J=5;break;case"thankyou":J=6;h=q;break;case"addpayoutcategory":if((typeof q!=B)&&(typeof q.id!=B)&&(typeof q.price!=B)){this.pc.push(q)}else{this.dg("invalid addPayoutCategory")}break;case"setdecimal":this.dc=this.ic(q);
break;case"setcurrency":this.cr=q;break;case"clear":this.tm=[];this.pm=[];break;case"setcoupon":this.cv=q;break;case"rtg":if(typeof q!=B&&q==0){this.rtg=0}break;default:this.lwde_add(G[0],q);break}}}if(this.p){var E=encodeURIComponent;var u="&decimal="+E(this.dk(this.dc));
switch(J){case 1:F="home";break;case 2:F="list";p=this.pida(E)+u;break;case 3:F="prod";p=this.pida(E)+u;break;case 4:F="cart";p=this.pida(E)+u;break;case 5:F="checkout";break;case 6:F="thanku";p=this.pida(E);if(h){if(typeof h.orderid!=B){p+="&trans_id="+E(h.orderid)
}var I=this.dc;if(typeof h.decimal!=B){I=this.ic(h.decimal);p+=("&decimal="+E(this.dk(I)))}else{p+=u}if((typeof h.duplicate==B)||h.duplicate=="false"||!h.duplicate){if(typeof h.subid==B){h.subid=""}if(typeof h.status==B){h.status="pending"}var z={};while(G=this.pc.shift()){this.zk(z,G.id,G.price,G.quantity,I,B)
}while(G=this.tm.shift()){this.zk(z,G.payout,G.price,G.quantity,I,B)}var C,d,A,f,s,b;var H=[];f=parseFloat(this.fi(this.cv,I));b=0;for(C in z){b++}if(isNaN(f)){this.dg("invalid coupon price: "+this.cv);f=0}s=(b>0)?Math.round(f*100):0;z=this.rc(z,s);for(C in z){d=String(z[C]);
A=d.length-2;if(A<1){d="0.00".substring(0,Math.abs(A)+2)+d}else{d=d.substring(0,A)+"."+d.substring(A)}H.push(C+"::"+d)}H=H.join("__");h.p=this.p;if(typeof h.currency==B){h.currency=this.cr}this.loadScript(this.url+"delivery/lwc/lwc.js",function(){Linkwise.currency(h.currency);
Linkwise.load_action(h.p,h.orderid,H,h.subid,h.status)})}else{p+="&duplicate=1"}}break}if(this.rtg==1){if(this.sr==1){var m="";if(F){m="&append_check=1"}this.is("ros",m);this.sr=2}if(F){this.is(F,p)}}if(this.p===6){this.lwde_add("page",F);this.lwde(E,p)}}}else{if(g++<20){setTimeout(function(){LWtpo.main(o,g)
},250)}}},rf:false,rl:[],reh:false,readyGo:function(){if(!this.rf){this.rf=true;for(var a=0;a<this.rl.length;a++){this.rl[a].fn.call(window,this.rl[a].ctx)}this.rl=[]}},rsc:function(a){if(a.readyState==="complete"){this.readyGo()}},ready:function(a,c){if(this.rf){setTimeout(function(){a(c)
},1);return}else{this.rl.push({fn:a,ctx:c})}var b=this;var f=function(){b.readyGo()};var e=document;if(e.readyState==="complete"){setTimeout(f,1)}else{if(!this.reh){if(e.addEventListener){e.addEventListener("DOMContentLoaded",f,false);window.addEventListener("load",f,false)
}else{e.attachEvent("onreadystatechange",function(){b.rsc(e)});window.attachEvent("onload",f)}this.reh=true}}}};var LWrtg=LWtpo;LWtpo.ready(function(){LWtpo.track(window);LWtpo.main(window)})}else{if(typeof LWtpo.ntl!=="undefined"&&LWtpo.ntl===1){LWtpo.ntl++;
if(typeof LWtpo.ready==="undefined"){LWtpo.rl.push({fn:function(){LWtpo.track(window)},ctx:"undefined"})}else{LWtpo.ready(function(){LWtpo.track(window)})}}};
